kind: Secret
apiVersion: v1
metadata:
  name: ansible
  namespace: policies
  labels:
    cluster.open-cluster-management.io/copiedFromNamespace: ansible-automation-platform
    cluster.open-cluster-management.io/copiedFromSecretName: ansible
    cluster.open-cluster-management.io/type: ans
  annotations:
    credential-hash: +XDsQgqLs5KU2m9FR/fP0bXB9JXbTTotbiNBRtv2ubc=
 data:
  host: >-
    aHR0cHM6Ly9hdXRvLWNvbnRyb2xsZXItYW5zaWJsZS1hdXRvbWF0aW9uLXBsYXRmb3JtLmFwcHMucG9saWN5LWdyYy1jcC1hdXRvY2xhaW1zLTZkeDU0LmRldjA4LnJlZC1jaGVzdGVyZmllbGQuY29t
  token: VEJBdWJ6VWFqTE9ucEh1RmFCSVJLRTNYRFo2OWdZ
type: Opaque
