apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ansible-secret
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: NIST, NIST-CSF
    policy.open-cluster-management.io/categories: PR.PT Protective Technology, PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.PT-1 Audit Logging, PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ansible-secret
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: ansible
                  namespace: policies
                  labels:
                    cluster.open-cluster-management.io/copiedFromNamespace: ansible-automation-platform
                    cluster.open-cluster-management.io/copiedFromSecretName: ansible
                    cluster.open-cluster-management.io/type: ans
                data:
                  host: aHR0cHM6Ly9hdXRvLWNvbnRyb2xsZXItYW5zaWJsZS1hdXRvbWF0aW9uLXBsYXRmb3JtLmFwcHMucG9saWN5LWdyYy1jcC1hdXRvY2xhaW1zLTZkeDU0LmRldjA4LnJlZC1jaGVzdGVyZmllbGQuY29t
                  token: VEJBdWJ6VWFqTE9ucEh1RmFCSVJLRTNYRFo2OWdZ
                type: Opaque
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-ansible-secret
  namespace: policies
placementRef:
  name: placement-policy-ansible-secret
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-ansible-secret
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-ansible-secret
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev

